### ISSUE TITLE
invalid syntax for logging_server

### ISSUE THREAD

**Issue by ShripadNighojkar** [PaloAltoNetworks/prismacloud_sqs_to_syslog#2]
Hello,

configured pre-req as per document, but getting invalid syntax error for logging_server. 

OUTPUT:
root@BLE01:/tmp/pcs_sqs_to_syslog-master# python poll_n_write.py
  File "poll_n_write.py", line 19
    logging_server = config.rl_syslog_host
                 ^
SyntaxError: invalid syntax
root@BLE01:/tmp/pcs_sqs_to_syslog-master#

**Comment by ebeuerle** [comment]
Can you provide what you put in the config file?

**Comment by ShripadNighojkar** [comment]
**Pre-requ output:**

root@BLE01:/tmp/pcs_sqs_to_syslog-master# python3 --version
Python 3.6.9
root@BLE01:/tmp/pcs_sqs_to_syslog-master# sudo pip install requests
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages
root@BLE01:/tmp/pcs_sqs_to_syslog-master# sudo pip install pyyaml
Requirement already satisfied: pyyaml in /usr/lib/python2.7/dist-packages
root@BLE01:/tmp/pcs_sqs_to_syslog-master#


**Configs.yml**
root@BLE01:/tmp/pcs_sqs_to_syslog-master# cat config/configs.yml
prisma_cloud:
  aws_region: ap-south-1
  aws_sqs_queue: https://sqs.ap-south-1.amazonaws.com/75********4/B*********prisma
  syslog_host: 10.128.24.81

**Comment by ebeuerle** [comment]
Make sure you don't have a space after the IP address.   The config file is a yaml file so it needs proper indenting to be processed correct.  Please confirm no trailing spaces on the lines and that there is indention for the 3 lines below prisma_cloud:

**Comment by ShripadNighojkar** [comment]
Hi,
no additinal spaces & indention is correct. same error.
I think ' logging_server' veriable is not avilable in included import.

root@BLE01:/tmp/pcs_sqs_to_syslog-master# python poll_n_write.py
  File "poll_n_write.py", line 19
    logging_server = config.rl_syslog_host
                 ^
SyntaxError: invalid syntax
root@BLE01:/tmp/pcs_sqs_to_syslog-master#

**Comment by ebeuerle** [comment]
I tested this last night with no issues.  Are you using an older version of the script? Line 19 is not the logging_server variable definition:

12 #Config setup for AWS and syslog
 13 config = lib.ConfigHelper()
 14 logging_server = config.rl_syslog_host
 15 REGION_NAME = config.rl_aws_region
 16 qname = config.rl_aws_queue
 17 poll_interval       = 5
 18 poll_duration       = 10
 19 MaxNumberOfMessages = 10
 20 VisibilityTimeout   = 3600

**Comment by ShripadNighojkar** [comment]
Hello,

I have redeploy from git, but now having diffrent error while running python3 poll_n_write.py & python poll_n_write.py.


root@BLE01:/tmp/pcs_sqs_to_syslog-master30# **python3 poll_n_write.py**
/usr/local/lib/python3.6/dist-packages/boto3/compat.py:88: PythonDeprecationWarning: Boto3 will no longer support Python 3.6 starting May 30, 2022. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.7 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)
Error: Unrecognized error
root@BFLINFANSIBLE01:/tmp/pcs_sqs_to_syslog-master30# **python poll_n_write.py**
Traceback (most recent call last):
  File "poll_n_write.py", line 7, in <module>
    import boto3
ImportError: No module named boto3
root@BLE01:/tmp/pcs_sqs_to_syslog-master30#


**Error even for:**

root@BFLINFANSIBLE01:/tmp/pcs_sqs_to_syslog-master30# **python3.7 poll_n_write.py**
Traceback (most recent call last):
  File "poll_n_write.py", line 7, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
root@BFLINFANSIBLE01:/tmp/pcs_sqs_to_syslog-master30#

**Available python:**
root@BFLINFANSIBLE01:/tmp/pcs_sqs_to_syslog-master30# python
python                                        python3.6                                     python3-config
python2                                       python3.6-config                              python3m
python2.7                                     python3.6m                                    python3m-config
python2.7-config                              python3.6m-config                             python-argcomplete-check-easy-install-script
python2-config                                python3.7                                     python-argcomplete-tcsh
python3                                       python3.7m                                    python-config

**Comment by ebeuerle** [comment]
It requires boto3 to be installed.  You can use pip to install it like requests and pyyaml.

**Comment by ShripadNighojkar** [comment]
Hi,
Done the boto3 & pyyaml installation.

I guess now stucked at Environment variables. Please help, Im new to configure.

root@BLE01:/tmp/pcs_sqs_to_syslog-master30# python3.7 poll_n_write.py
Error: Unrecognized error
root@BLE01:/tmp/pcs_sqs_to_syslog-master30#

**Comment by ebeuerle** [comment]
Refer to here for configuration options: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html

**Comment by ShripadNighojkar** [comment]
Hi,

I guess this last error. Is any specific access is required for SQS?

(my-project-env) root@BLE01:/tmp/pcs_sqs_to_syslog-master30# python3.7 poll_n_write.py
**Error:  The specified queue does not exist**
(my-project-env) root@BLE01:/tmp/pcs_sqs_to_syslog-master30#


**SQS access policy:**
{
  "Version": "2012-10-17",
  "Id": "arn:aws:sqs:ap-south-1:********0004:B**-Marketing-*******/SQSDefaultPolicy",
  "Statement": [
    {
      "Sid": "Sid1586**********",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "SQS:*",
      "Resource": "arn:aws:sqs:ap-south-1:********0004:B**-Marketing-*******"
    },
    {
      "Sid": "topic-subscription-arn:aws:sns:ap-south-1:********0004:P******-config-alerts",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "SQS:SendMessage",
      "Resource": "arn:aws:sqs:ap-south-1:********0004:B**-Marketing-*******",
      "Condition": {
        "ArnLike": {
          "aws:SourceArn": "arn:aws:sns:ap-south-1:********0004:P****-config-alerts"
        }
      }
    }
  ]
}

**Comment by ebeuerle** [comment]
Yes, you need:

   -

   sqs:ListQueues

   -

   sqs:SendMessage

   -

   sqs:GetQueueUrl
